### ISSUE TITLE
Weight file

### ISSUE THREAD

**Issue by SrinjaySarkar** [gmum/points2nerf#2]
Could you please provide the weight file for any of the "airplanes"  or "chair" class ? Or even just the training loss logs? I am trying to train my model and your logs or weight file would be very helpful.

**Comment by Ideefixze** [comment]
Yes. 

Here's the link for weights for configs from repository. Weights should be put in experiment folder so that they might be loaded on startup. Currently, code works so it might need losses data, but if you don't need them and still want to load data it should be easy for you to edit pts2nerf.py for it to work without losses

I'll also put this link in README.md for future use

https://drive.google.com/drive/folders/1dcSxbXfSYpwjcazrVsHm3WNWcB8uPps-?usp=sharing

**Comment by SrinjaySarkar** [comment]
Thank you very much @Ideefixze .
