### ISSUE TITLE
render.py get black image

### ISSUE THREAD

**Issue by perisage** [gmum/points2nerf#5]
Thanks for the amazing work!
 
I have two questoins:

1. I got black images when using render.py to render shapenet data. The image is shown as below:

![image_0](https://user-images.githubusercontent.com/22021885/190347165-053bd5bf-8988-413d-b9ca-67a05c336a75.png)

2. There is no depth map file output.  the only files I got are black images.

---

my environment:
OS: Ubuntu18.04
Blender: 3.3

Do you know what's wrong with it? Thanks!

**Comment by perisage** [comment]
The first problem is caused by blender version. Downgrading blender to the 2.93LTS version solved the problem. But still no depth file output.  Can anybody help? Thanks!

**Comment by Ideefixze** [comment]
Hi,

we didn't generate depth images since they are not needed for training. However, if you still need it for any other reason try to check source codes we found helpful:
https://github.com/panmari/stanford-shapenet-renderer/blob/master/render_blender.py

https://github.com/bmild
(render scripts are in blender files named blend_files.zip from dataset, you can see the code in blender scripts)

**Comment by perisage** [comment]
> ou can see the code in blender scripts

Got it, Thanks!
